export const storesTypes = Object.freeze({
  FETCH_ALL_STORES: 'FETCH_ALL_STORES',
  FETCH_SEARCHED_STORE: 'FETCH_SEARCHED_STORE',
  FETCH_ALL_STORES_RESPONSE: 'FETCH_ALL_STORES_RESPONSE',
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
});
